
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parivesh2-dev
spec:
  selector:
    matchLabels:
      app: parivesh2-dev
  replicas: 1
  template:
    metadata:
      labels:
        app: parivesh2-dev
    spec:
      containers:
        - name: parivesh2-dev
          image: rohitkr115/parivesh2_dev:4.0
         # imagePullPolicy: Never
          ports:
            - containerPort: 9090
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: parivesh2-dev-svc
spec:
  selector:
    app: parivesh2-dev
  ports:
    - protocol: "TCP"
      port: 9090 # The port that the service is running on in the cluster
      targetPort: 9090 # The port exposed by the service
  type: NodePort # type of the service.
